### PR TITLE
pass in extra arg to ClientEnv, closes #1

### LINKED ISSUE #1: Fix servant issue. Resubmit to stackage-nightly and lts-11
See openai/gym-http-api#64 and commercialhaskell/stackage#3354

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**

### CODE REVIEW

**Comment by stites** [comment]
haha! thanks for this! Note that all changes to master are being pushed to openai/gym-http-api#57

**Comment by stites** [comment]
Oooh, we broke backwards compatibility without a version bump. I think the more correct way to do this was to add a CPP version flag depending on the servant version... that fix will have to be made before reintroducing this to {h/st}ackage.

**Comment by KiaraGrouwstra** [comment]
hmm. can't we control the servant version?

**Comment by stites** [comment]
It would require a Hackage version bump... Which I guess is a valid patch update. I'll try to get around to it this weekend.

**Pull request merged**
